### ISSUE TITLE
Tasks and Assigns

### ISSUE THREAD

**Issue by changami** [changami/a_certain_file_uploader#3]
画面
---

- [x] ログイン画面 chan_gami
- [x] ログアウト画面 chan_gami
- [ ] ユーザー作成画面 chan_gami
- [x] ファイル操作画面 mossuru777
- [x] ユーザごとのファイル操作履歴画面 mossuru777
- [x] アップロードしたファイル一覧画面 mossuru777
- [ ] 設定画面(管理者のみ) chan_gami

機能
---

- [x] ログインchan_gami
- [x] ログアウト chan_gami
- [x] ユーザーがログインしていない時にログインページに遷移させる mossuru777
- [ ] ログインユーザー 一般/管理者権限の分離 chan_gami
- [x] ファイルアップロード mossuru777
- [x] ファイルダウンロード mossuru777
- [x] ファイル削除 mossuru777
- [x] ユーザごとのファイル操作履歴 mossuru777
- [x] 合計ファイル容量制限 mossuru777
- [x] [合計ファイル容量制限]を変更できる(管理者のみ) mossuru777
- [ ] i18n対応(デフォルト言語は英語) 

設計
---

- [ ] メッセージクリアのタイミング

**Comment by changami** [comment]
あれ、 053d338cd18f256f011a96ed1b59af854e4c9b0b でRubyのVersion上げた理由ってなんだっけ？

**Comment by Mossuru777** [comment]
新しいマシンなどでrbenvを新しく使うときに  
どのバージョンを使うか明示する.ruby-versionを作成しようということになって、  
Ruby 2.1系を使用して開発を行っていたため、  
その時点での最新バージョンを記して作成したかと思います。

**Comment by changami** [comment]
ふたりで話し合った結果、nodeで作り直すことになりましたのでcloseいたします。
