### ISSUE TITLE
flashクリアの実装優先度について

### ISSUE THREAD

**Issue by Mossuru777** [changami/a_certain_file_uploader#8]
当初予定していた機能の実装のほとんどが終了し、
@changami 氏のユーザー登録/設定画面回りの実装を残すのみとなりましたが、
#6 で言及されていたflash[:alert]やflash[:notice]を必要な箇所でクリアする実装について、
全機能実装後に行おうと考えていますがいかがでしょうか。

**Comment by changami** [comment]
ふたりで話し合った結果、nodeで作り直すことになりましたのでcloseいたします。
